name: Build/Test Docker Containers
on:
  push:
    branches:
      - main
env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker build -t sudo1amir/react-test -f ./client/Dockerfile.dev ./client/
          docker run -e CI=true rallycoding/react-test npm test
      - name: Build
        run: |-
          docker build -t sudo1amir/multi-client-k8s:latest -t sudo1amir/multi-client-k8s:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t sudo1amir/multi-server-k8s:latest -t sudo1amir/multi-server-k8s:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t sudo1amir/multi-worker-k8s:latest -t sudo1amir/multi-worker-k8s:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push
        run: |-
        
          docker push sudo1amir/multi-client-k8s:latest
          docker push sudo1amir/multi-server-k8s:latest
          docker push sudo1amir/multi-worker-k8s:latest

          docker push sudo1amir/multi-client-k8s:${{ env.SHA }}
          docker push sudo1amir/multi-server-k8s:${{ env.SHA }}
          docker push sudo1amir/multi-worker-k8s:${{ env.SHA }}
